### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by thewindboi**

### CODE REVIEW

**Comment by neeeerrd** [comment]
this is useless and will be difficult to maintain

**Comment by Bananattttx** [comment]
holy hell!

**Comment by thewindboi** [comment]
how is a readme.md gonna be difficult to maintain 💀

**Comment by neeeerrd** [comment]
a readme.md requires constant updating to keep up with new features, etc.

**Comment by neeeerrd** [comment]
could you please explain why this project needs a readme?

**Comment by thewindboi** [comment]
cus h
#

**Comment by neeeerrd** [comment]
its useless.

**Comment by Bananattttx** [comment]
h :)

**Pull request closed without merging**
